package models;

// Generated 12/06/2014 09:03:18 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TbasicData generated by hbm2java
 */
@Entity
@Table(name = "tbasic_data", schema = "public")
public class TbasicData implements java.io.Serializable {

    private static final long serialVersionUID = -3154517256350853336L;
	private int idBasicData;
	private TdataType tdataType;
	private TbasicData tbasicData;
	private String name;
	private String description;
	private boolean editable;
	private char status;
	private Set<TbasicData> tbasicDatas = new HashSet<TbasicData>(0);
	private Set<Titem> titemsForType = new HashSet<Titem>(0);
	private Set<TbusinessPartnerBranch> tbusinessPartnerBranches = new HashSet<TbusinessPartnerBranch>(0);
	private Set<TorderDetail> torderDetails = new HashSet<TorderDetail>(0);
	private Set<Tbill> tbills = new HashSet<Tbill>(0);
	private Set<Titem> titemsForUnitCar = new HashSet<Titem>(0);
	private Set<TbusinessPartner> tbusinessPartnersForRifType = new HashSet<TbusinessPartner>(0);
	private Set<TbusinessPartner> tbusinessPartnersForType = new HashSet<TbusinessPartner>(0);

	public TbasicData() {
	}

	public TbasicData(int idBasicData, TdataType tdataType, String name, boolean editable, char status) {
		this.idBasicData = idBasicData;
		this.tdataType = tdataType;
		this.name = name;
		this.editable = editable;
		this.status = status;
	}

	public TbasicData(int idBasicData, TdataType tdataType, TbasicData tbasicData, String name, String description, boolean editable, char status, Set<TbasicData> tbasicDatas, Set<Titem> titemsForType, Set<TbusinessPartnerBranch> tbusinessPartnerBranches, Set<TorderDetail> torderDetails, Set<Tbill> tbills, Set<Titem> titemsForUnitCar, Set<TbusinessPartner> tbusinessPartnersForRifType, Set<TbusinessPartner> tbusinessPartnersForType) {
		this.idBasicData = idBasicData;
		this.tdataType = tdataType;
		this.tbasicData = tbasicData;
		this.name = name;
		this.description = description;
		this.editable = editable;
		this.status = status;
		this.tbasicDatas = tbasicDatas;
		this.titemsForType = titemsForType;
		this.tbusinessPartnerBranches = tbusinessPartnerBranches;
		this.torderDetails = torderDetails;
		this.tbills = tbills;
		this.titemsForUnitCar = titemsForUnitCar;
		this.tbusinessPartnersForRifType = tbusinessPartnersForRifType;
		this.tbusinessPartnersForType = tbusinessPartnersForType;
	}

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "tbasic_data_id_seq")
    @SequenceGenerator(name = "tbasic_data_id_seq", sequenceName = "tbasic_data_id_seq")
	@Column(name = "id_basic_data", unique = true, nullable = false)
	public int getIdBasicData() {
		return this.idBasicData;
	}

	public void setIdBasicData(int idBasicData) {
		this.idBasicData = idBasicData;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_data_type", nullable = false)
	public TdataType getTdataType() {
		return this.tdataType;
	}

	public void setTdataType(TdataType tdataType) {
		this.tdataType = tdataType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id_basic")
	public TbasicData getTbasicData() {
		return this.tbasicData;
	}

	public void setTbasicData(TbasicData tbasicData) {
		this.tbasicData = tbasicData;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "editable", nullable = false)
	public boolean isEditable() {
		return this.editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicData")
	public Set<TbasicData> getTbasicDatas() {
		return this.tbasicDatas;
	}

	public void setTbasicDatas(Set<TbasicData> tbasicDatas) {
		this.tbasicDatas = tbasicDatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicDataByType")
	public Set<Titem> getTitemsForType() {
		return this.titemsForType;
	}

	public void setTitemsForType(Set<Titem> titemsForType) {
		this.titemsForType = titemsForType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicData")
	public Set<TbusinessPartnerBranch> getTbusinessPartnerBranches() {
		return this.tbusinessPartnerBranches;
	}

	public void setTbusinessPartnerBranches(Set<TbusinessPartnerBranch> tbusinessPartnerBranches) {
		this.tbusinessPartnerBranches = tbusinessPartnerBranches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicData")
	public Set<TorderDetail> getTorderDetails() {
		return this.torderDetails;
	}

	public void setTorderDetails(Set<TorderDetail> torderDetails) {
		this.torderDetails = torderDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicData")
	public Set<Tbill> getTbills() {
		return this.tbills;
	}

	public void setTbills(Set<Tbill> tbills) {
		this.tbills = tbills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicDataByUnitCar")
	public Set<Titem> getTitemsForUnitCar() {
		return this.titemsForUnitCar;
	}

	public void setTitemsForUnitCar(Set<Titem> titemsForUnitCar) {
		this.titemsForUnitCar = titemsForUnitCar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicDataByRifType")
	public Set<TbusinessPartner> getTbusinessPartnersForRifType() {
		return this.tbusinessPartnersForRifType;
	}

	public void setTbusinessPartnersForRifType(Set<TbusinessPartner> tbusinessPartnersForRifType) {
		this.tbusinessPartnersForRifType = tbusinessPartnersForRifType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicDataByType")
	public Set<TbusinessPartner> getTbusinessPartnersForType() {
		return this.tbusinessPartnersForType;
	}

	public void setTbusinessPartnersForType(Set<TbusinessPartner> tbusinessPartnersForType) {
		this.tbusinessPartnersForType = tbusinessPartnersForType;
	}

}
