package models;

// Generated 10/07/2014 10:58:58 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbusinesPartnerItemId generated by hbm2java
 */
@Embeddable
public class TbusinesPartnerItemId implements java.io.Serializable {

	private static final long serialVersionUID = -8457989764895059196L;
	private int idBusinessPartner;
	private int idItem;

	public TbusinesPartnerItemId() {
	}

	public TbusinesPartnerItemId(int idBusinessPartner, int idItem) {
		this.idBusinessPartner = idBusinessPartner;
		this.idItem = idItem;
	}

	@Column(name = "id_business_partner", nullable = false)
	public int getIdBusinessPartner() {
		return this.idBusinessPartner;
	}

	public void setIdBusinessPartner(int idBusinessPartner) {
		this.idBusinessPartner = idBusinessPartner;
	}

	@Column(name = "id_item", nullable = false)
	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbusinesPartnerItemId))
			return false;
		TbusinesPartnerItemId castOther = (TbusinesPartnerItemId) other;

		return (this.getIdBusinessPartner() == castOther.getIdBusinessPartner()) && (this.getIdItem() == castOther.getIdItem());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdBusinessPartner();
		result = 37 * result + this.getIdItem();
		return result;
	}

}
