package models;

// Generated 12/06/2014 09:35:54 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TinputMeasureUnit generated by hbm2java
 */
@Entity
@Table(name = "tinput_measure_unit", schema = "public")
public class TinputMeasureUnit implements java.io.Serializable {

	private static final long serialVersionUID = -8188724073871547310L;
	private int idInputMeasureUnit;
	private Titem titem;
	private TbasicData tbasicData;
	private float weightUnit;
	private char status;

	public TinputMeasureUnit() {
	}

	public TinputMeasureUnit(int idInputMeasureUnit, Titem titem, TbasicData tbasicData, float weightUnit, char status) {
		this.idInputMeasureUnit = idInputMeasureUnit;
		this.titem = titem;
		this.tbasicData = tbasicData;
		this.weightUnit = weightUnit;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "tinput_measure_unit_id_seq")
    @SequenceGenerator(name = "tinput_measure_unit_id_seq", sequenceName = "tinput_measure_unit_id_input_measure_unit_seq")
	@Column(name = "id_input_measure_unit", unique = true, nullable = false)
	public int getIdInputMeasureUnit() {
		return this.idInputMeasureUnit;
	}

	public void setIdInputMeasureUnit(int idInputMeasureUnit) {
		this.idInputMeasureUnit = idInputMeasureUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_item", nullable = false)
	public Titem getTitem() {
		return this.titem;
	}

	public void setTitem(Titem titem) {
		this.titem = titem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measure_unit", nullable = false)
	public TbasicData getTbasicData() {
		return this.tbasicData;
	}

	public void setTbasicData(TbasicData tbasicData) {
		this.tbasicData = tbasicData;
	}

	@Column(name = "weight_unit", nullable = false, precision = 8, scale = 8)
	public float getWeightUnit() {
		return this.weightUnit;
	}

	public void setWeightUnit(float weightUnit) {
		this.weightUnit = weightUnit;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
