package models;

// Generated 03/09/2014 09:02:10 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TpurchaseDetail generated by hbm2java
 */
@Entity
@Table(name = "tpurchase_detail", schema = "public")
public class TpurchaseDetail implements java.io.Serializable {

	private static final long serialVersionUID = -7901127062084404923L;
	private int idPurchaseDetail;
	private Tpurchase tpurchase;
	private Titem titem;
	private TbasicData tbasicData;
	private String itemName;
	private float quantity;
	private char status;

	public TpurchaseDetail() {
	}

	public TpurchaseDetail(int idPurchaseDetail, Tpurchase tpurchase, Titem titem, TbasicData tbasicData, String itemName, float quantity, char status) {
		this.idPurchaseDetail = idPurchaseDetail;
		this.tpurchase = tpurchase;
		this.titem = titem;
		this.tbasicData = tbasicData;
		this.itemName = itemName;
		this.quantity = quantity;
		this.status = status;
	}

	@Id
	@Column(name = "id_purchase_detail", unique = true, nullable = false)
	public int getIdPurchaseDetail() {
		return this.idPurchaseDetail;
	}

	public void setIdPurchaseDetail(int idPurchaseDetail) {
		this.idPurchaseDetail = idPurchaseDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_purchase", nullable = false)
	public Tpurchase getTpurchase() {
		return this.tpurchase;
	}

	public void setTpurchase(Tpurchase tpurchase) {
		this.tpurchase = tpurchase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_item", nullable = false)
	public Titem getTitem() {
		return this.titem;
	}

	public void setTitem(Titem titem) {
		this.titem = titem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measure_unit", nullable = false)
	public TbasicData getTbasicData() {
		return this.tbasicData;
	}

	public void setTbasicData(TbasicData tbasicData) {
		this.tbasicData = tbasicData;
	}

	@Column(name = "item_name", nullable = false, length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "quantity", nullable = false, precision = 8, scale = 8)
	public float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(float quantity) {
		this.quantity = quantity;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
