package models;

// Generated 02/11/2014 09:38:14 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Troute generated by hbm2java
 */
@Entity
@Table(name = "troute", schema = "public")
public class Troute implements java.io.Serializable {

	private static final long serialVersionUID = -8475231006609560337L;
	private int idRoute;
	private String code;
	private String description;
	private char status;
	private Set<TbusinessPartnerBranch> tbusinessPartnerBranches = new HashSet<TbusinessPartnerBranch>(0);
	private Set<Twaybill> twaybills = new HashSet<Twaybill>(0);

	public Troute() {
	}

	public Troute(int idRoute, String code, String description, char status) {
		this.idRoute = idRoute;
		this.code = code;
		this.description = description;
		this.status = status;
	}

	public Troute(int idRoute, String code, String description, char status, Set<TbusinessPartnerBranch> tbusinessPartnerBranches, Set<Twaybill> twaybills) {
		this.idRoute = idRoute;
		this.code = code;
		this.description = description;
		this.status = status;
		this.tbusinessPartnerBranches = tbusinessPartnerBranches;
		this.twaybills = twaybills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "troute_id_seq")
	@SequenceGenerator(name = "troute_id_seq", sequenceName = "troute_id_route_seq")
	@Column(name = "id_route", unique = true, nullable = false)
	public int getIdRoute() {
		return this.idRoute;
	}

	public void setIdRoute(int idRoute) {
		this.idRoute = idRoute;
	}

	@Column(name = "code", nullable = false, length = 40)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false, length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tbusiness_partner_route", schema = "public", joinColumns = { @JoinColumn(name = "id_route", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_business_partner_branch", nullable = false, updatable = false) })
	public Set<TbusinessPartnerBranch> getTbusinessPartnerBranches() {
		return this.tbusinessPartnerBranches;
	}

	public void setTbusinessPartnerBranches(Set<TbusinessPartnerBranch> tbusinessPartnerBranches) {
		this.tbusinessPartnerBranches = tbusinessPartnerBranches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "troute")
	public Set<Twaybill> getTwaybills() {
		return this.twaybills;
	}

	public void setTwaybills(Set<Twaybill> twaybills) {
		this.twaybills = twaybills;
	}

}
