package models;

// Generated 02/11/2014 09:38:14 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tvehicle generated by hbm2java
 */
@Entity
@Table(name = "tvehicle", schema = "public")
public class Tvehicle implements java.io.Serializable {

	private static final long serialVersionUID = -6271502501214048969L;
	private int idVehicle;
	private TbasicData tbasicData;
	private String docNum;
	private String model;
	private String owner;
	private float capacity;
	private String comment;
	private char status;
	private Set<Twaybill> twaybills = new HashSet<Twaybill>(0);

	public Tvehicle() {
	}

	public Tvehicle(int idVehicle, TbasicData tbasicData, String docNum, String model, String owner, float capacity, String comment, char status) {
		this.idVehicle = idVehicle;
		this.tbasicData = tbasicData;
		this.docNum = docNum;
		this.model = model;
		this.owner = owner;
		this.capacity = capacity;
		this.comment = comment;
		this.status = status;
	}

	public Tvehicle(int idVehicle, TbasicData tbasicData, String docNum, String model, String owner, float capacity, String comment, char status, Set<Twaybill> twaybills) {
		this.idVehicle = idVehicle;
		this.tbasicData = tbasicData;
		this.docNum = docNum;
		this.model = model;
		this.owner = owner;
		this.capacity = capacity;
		this.comment = comment;
		this.status = status;
		this.twaybills = twaybills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "tvehicle_id_seq")
	@SequenceGenerator(name = "tvehicle_id_seq", sequenceName = "tvehicle_id_vehicle_seq")
	@Column(name = "id_vehicle", unique = true, nullable = false)
	public int getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(int idVehicle) {
		this.idVehicle = idVehicle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measure_unit", nullable = false)
	public TbasicData getTbasicData() {
		return this.tbasicData;
	}

	public void setTbasicData(TbasicData tbasicData) {
		this.tbasicData = tbasicData;
	}

	@Column(name = "doc_num", nullable = false, length = 15)
	public String getDocNum() {
		return this.docNum;
	}

	public void setDocNum(String docNum) {
		this.docNum = docNum;
	}

	@Column(name = "model", nullable = false, length = 100)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "owner", nullable = false, length = 100)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "capacity", nullable = false, precision = 8, scale = 8)
	public float getCapacity() {
		return this.capacity;
	}

	public void setCapacity(float capacity) {
		this.capacity = capacity;
	}

	@Column(name = "comment", nullable = false, length = 450)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tvehicle")
	public Set<Twaybill> getTwaybills() {
		return this.twaybills;
	}

	public void setTwaybills(Set<Twaybill> twaybills) {
		this.twaybills = twaybills;
	}

}
