package database;

// Generated 10-oct-2012 10:59:39 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sgroup generated by hbm2java
 */
@Entity
@Table(name = "sgroup")
public class Sgroup implements java.io.Serializable {

	private int idg;
	private Tbasicdata tbasicdata;
	private String name;
	private int status;
	private Set susers = new HashSet(0);
	private Set sroles = new HashSet(0);

	public Sgroup() {
	}

	public Sgroup(int idg, Tbasicdata tbasicdata, String name, int status) {
		this.idg = idg;
		this.tbasicdata = tbasicdata;
		this.name = name;
		this.status = status;
	}

	public Sgroup(int idg, Tbasicdata tbasicdata, String name, int status,
			Set susers, Set sroles) {
		this.idg = idg;
		this.tbasicdata = tbasicdata;
		this.name = name;
		this.status = status;
		this.susers = susers;
		this.sroles = sroles;
	}

	@Id
	@Column(name = "idg", unique = true, nullable = false)
	public int getIdg() {
		return this.idg;
	}

	public void setIdg(int idg) {
		this.idg = idg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbasic", nullable = false)
	public Tbasicdata getTbasicdata() {
		return this.tbasicdata;
	}

	public void setTbasicdata(Tbasicdata tbasicdata) {
		this.tbasicdata = tbasicdata;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "sgroupuser", joinColumns = { @JoinColumn(name = "idg", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idu", nullable = false, updatable = false) })
	public Set getSusers() {
		return this.susers;
	}

	public void setSusers(Set susers) {
		this.susers = susers;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "sgroups")
	public Set getSroles() {
		return this.sroles;
	}

	public void setSroles(Set sroles) {
		this.sroles = sroles;
	}

}
