package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sgroupuser generated by hbm2java
 */
@Entity
@Table(name = "sgroupuser")
public class Sgroupuser implements java.io.Serializable {

	private SgroupuserId id;
	private Suser suser;
	private Sgroup sgroup;
	private int status;

	public Sgroupuser() {
	}

	public Sgroupuser(SgroupuserId id, Suser suser, Sgroup sgroup, int status) {
		this.id = id;
		this.suser = suser;
		this.sgroup = sgroup;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idg", column = @Column(name = "idg", nullable = false)),
			@AttributeOverride(name = "idu", column = @Column(name = "idu", nullable = false)) })
	public SgroupuserId getId() {
		return this.id;
	}

	public void setId(SgroupuserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idu", nullable = false, insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idg", nullable = false, insertable = false, updatable = false)
	public Sgroup getSgroup() {
		return this.sgroup;
	}

	public void setSgroup(Sgroup sgroup) {
		this.sgroup = sgroup;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
