package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sgroup generated by hbm2java
 */
@Entity
@Table(name = "sgroup")
public class Sgroup implements java.io.Serializable {

	private int idg;
	private String name;
	private int status;
	private Set sgroupusers = new HashSet(0);
	private Set srolegroups = new HashSet(0);

	public Sgroup() {
	}

	public Sgroup(int idg, String name, int status) {
		this.idg = idg;
		this.name = name;
		this.status = status;
	}

	public Sgroup(int idg, String name, int status, Set sgroupusers,
			Set srolegroups) {
		this.idg = idg;
		this.name = name;
		this.status = status;
		this.sgroupusers = sgroupusers;
		this.srolegroups = srolegroups;
	}

	@Id
	@Column(name = "idg", unique = true, nullable = false)
	public int getIdg() {
		return this.idg;
	}

	public void setIdg(int idg) {
		this.idg = idg;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgroup")
	public Set getSgroupusers() {
		return this.sgroupusers;
	}

	public void setSgroupusers(Set sgroupusers) {
		this.sgroupusers = sgroupusers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgroup")
	public Set getSrolegroups() {
		return this.srolegroups;
	}

	public void setSrolegroups(Set srolegroups) {
		this.srolegroups = srolegroups;
	}

}
