package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgroupuserId generated by hbm2java
 */
@Embeddable
public class SgroupuserId implements java.io.Serializable {

	private int idg;
	private int idu;

	public SgroupuserId() {
	}

	public SgroupuserId(int idg, int idu) {
		this.idg = idg;
		this.idu = idu;
	}

	@Column(name = "idg", nullable = false)
	public int getIdg() {
		return this.idg;
	}

	public void setIdg(int idg) {
		this.idg = idg;
	}

	@Column(name = "idu", nullable = false)
	public int getIdu() {
		return this.idu;
	}

	public void setIdu(int idu) {
		this.idu = idu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SgroupuserId))
			return false;
		SgroupuserId castOther = (SgroupuserId) other;

		return (this.getIdg() == castOther.getIdg())
				&& (this.getIdu() == castOther.getIdu());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdg();
		result = 37 * result + this.getIdu();
		return result;
	}

}
