package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SrolegroupId generated by hbm2java
 */
@Embeddable
public class SrolegroupId implements java.io.Serializable {

	private int idr;
	private int idg;

	public SrolegroupId() {
	}

	public SrolegroupId(int idr, int idg) {
		this.idr = idr;
		this.idg = idg;
	}

	@Column(name = "idr", nullable = false)
	public int getIdr() {
		return this.idr;
	}

	public void setIdr(int idr) {
		this.idr = idr;
	}

	@Column(name = "idg", nullable = false)
	public int getIdg() {
		return this.idg;
	}

	public void setIdg(int idg) {
		this.idg = idg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SrolegroupId))
			return false;
		SrolegroupId castOther = (SrolegroupId) other;

		return (this.getIdr() == castOther.getIdr())
				&& (this.getIdg() == castOther.getIdg());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdr();
		result = 37 * result + this.getIdg();
		return result;
	}

}
