package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Srole generated by hbm2java
 */
@Entity
@Table(name = "srole")
public class Srole implements java.io.Serializable {

	private int idr;
	private char status;
	private String name;
	private Set srolegroups = new HashSet(0);

	public Srole() {
	}

	public Srole(int idr, char status, String name) {
		this.idr = idr;
		this.status = status;
		this.name = name;
	}

	public Srole(int idr, char status, String name, Set srolegroups) {
		this.idr = idr;
		this.status = status;
		this.name = name;
		this.srolegroups = srolegroups;
	}

	@Id
	@Column(name = "idr", unique = true, nullable = false)
	public int getIdr() {
		return this.idr;
	}

	public void setIdr(int idr) {
		this.idr = idr;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srole")
	public Set getSrolegroups() {
		return this.srolegroups;
	}

	public void setSrolegroups(Set srolegroups) {
		this.srolegroups = srolegroups;
	}

}
