package database;

// Generated 10-oct-2012 10:59:39 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Srole generated by hbm2java
 */
@Entity
@Table(name = "srole")
public class Srole implements java.io.Serializable {

	private int idr;
	private Tbasicdata tbasicdata;
	private String name;
	private Set sgroups = new HashSet(0);

	public Srole() {
	}

	public Srole(int idr, Tbasicdata tbasicdata, String name) {
		this.idr = idr;
		this.tbasicdata = tbasicdata;
		this.name = name;
	}

	public Srole(int idr, Tbasicdata tbasicdata, String name, Set sgroups) {
		this.idr = idr;
		this.tbasicdata = tbasicdata;
		this.name = name;
		this.sgroups = sgroups;
	}

	@Id
	@Column(name = "idr", unique = true, nullable = false)
	public int getIdr() {
		return this.idr;
	}

	public void setIdr(int idr) {
		this.idr = idr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbasic", nullable = false)
	public Tbasicdata getTbasicdata() {
		return this.tbasicdata;
	}

	public void setTbasicdata(Tbasicdata tbasicdata) {
		this.tbasicdata = tbasicdata;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "srolegroup", joinColumns = { @JoinColumn(name = "idr", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idg", nullable = false, updatable = false) })
	public Set getSgroups() {
		return this.sgroups;
	}

	public void setSgroups(Set sgroups) {
		this.sgroups = sgroups;
	}

}
