package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Srolegroup generated by hbm2java
 */
@Entity
@Table(name = "srolegroup")
public class Srolegroup implements java.io.Serializable {

	private SrolegroupId id;
	private Sgroup sgroup;
	private Srole srole;
	private int status;

	public Srolegroup() {
	}

	public Srolegroup(SrolegroupId id, Sgroup sgroup, Srole srole, int status) {
		this.id = id;
		this.sgroup = sgroup;
		this.srole = srole;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idr", column = @Column(name = "idr", nullable = false)),
			@AttributeOverride(name = "idg", column = @Column(name = "idg", nullable = false)) })
	public SrolegroupId getId() {
		return this.id;
	}

	public void setId(SrolegroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idg", nullable = false, insertable = false, updatable = false)
	public Sgroup getSgroup() {
		return this.sgroup;
	}

	public void setSgroup(Sgroup sgroup) {
		this.sgroup = sgroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idr", nullable = false, insertable = false, updatable = false)
	public Srole getSrole() {
		return this.srole;
	}

	public void setSrole(Srole srole) {
		this.srole = srole;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
