package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Suser generated by hbm2java
 */
@Entity
@Table(name = "suser")
public class Suser implements java.io.Serializable {

	private int idu;
	private String name;
	private String email;
	private String password;
	private char status;
	private Set sgroupusers = new HashSet(0);

	public Suser() {
	}

	public Suser(int idu, String name, String email, String password,
			char status) {
		this.idu = idu;
		this.name = name;
		this.email = email;
		this.password = password;
		this.status = status;
	}

	public Suser(int idu, String name, String email, String password,
			char status, Set sgroupusers) {
		this.idu = idu;
		this.name = name;
		this.email = email;
		this.password = password;
		this.status = status;
		this.sgroupusers = sgroupusers;
	}

	@Id
	@Column(name = "idu", unique = true, nullable = false)
	public int getIdu() {
		return this.idu;
	}

	public void setIdu(int idu) {
		this.idu = idu;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "suser")
	public Set getSgroupusers() {
		return this.sgroupusers;
	}

	public void setSgroupusers(Set sgroupusers) {
		this.sgroupusers = sgroupusers;
	}

}
