package database;

// Generated 10-oct-2012 10:59:39 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Suser generated by hbm2java
 */
@Entity
@Table(name = "suser")
public class Suser implements java.io.Serializable {

	private int idu;
	private Tbasicdata tbasicdata;
	private String name;
	private String email;
	private String password;
	private Set sgroups = new HashSet(0);

	public Suser() {
	}

	public Suser(int idu, Tbasicdata tbasicdata, String name, String email,
			String password) {
		this.idu = idu;
		this.tbasicdata = tbasicdata;
		this.name = name;
		this.email = email;
		this.password = password;
	}

	public Suser(int idu, Tbasicdata tbasicdata, String name, String email,
			String password, Set sgroups) {
		this.idu = idu;
		this.tbasicdata = tbasicdata;
		this.name = name;
		this.email = email;
		this.password = password;
		this.sgroups = sgroups;
	}

	@Id
	@Column(name = "idu", unique = true, nullable = false)
	public int getIdu() {
		return this.idu;
	}

	public void setIdu(int idu) {
		this.idu = idu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbasic", nullable = false)
	public Tbasicdata getTbasicdata() {
		return this.tbasicdata;
	}

	public void setTbasicdata(Tbasicdata tbasicdata) {
		this.tbasicdata = tbasicdata;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "susers")
	public Set getSgroups() {
		return this.sgroups;
	}

	public void setSgroups(Set sgroups) {
		this.sgroups = sgroups;
	}

}
