package database;

// Generated 10-oct-2012 10:59:39 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbasicdata generated by hbm2java
 */
@Entity
@Table(name = "tbasicdata")
public class Tbasicdata implements java.io.Serializable {

	private int idbasic;
	private Tbasicdata tbasicdata;
	private String database;
	private String name;
	private String description;
	private boolean editable;
	private int status;
	private Set tbusinesspartners = new HashSet(0);
	private Set tbills = new HashSet(0);
	private Set tbasicdatas = new HashSet(0);
	private Set sroles = new HashSet(0);
	private Set tbilldetails = new HashSet(0);
	private Set torderdetails = new HashSet(0);
	private Set sgroups = new HashSet(0);
	private Set susers = new HashSet(0);
	private Set torders = new HashSet(0);
	private Set titems = new HashSet(0);
	private Set tbusinesspartneraddresses = new HashSet(0);

	public Tbasicdata() {
	}

	public Tbasicdata(int idbasic, Tbasicdata tbasicdata, String database,
			String name, boolean editable, int status) {
		this.idbasic = idbasic;
		this.tbasicdata = tbasicdata;
		this.database = database;
		this.name = name;
		this.editable = editable;
		this.status = status;
	}

	public Tbasicdata(int idbasic, Tbasicdata tbasicdata, String database,
			String name, String description, boolean editable, int status,
			Set tbusinesspartners, Set tbills, Set tbasicdatas, Set sroles,
			Set tbilldetails, Set torderdetails, Set sgroups, Set susers,
			Set torders, Set titems, Set tbusinesspartneraddresses) {
		this.idbasic = idbasic;
		this.tbasicdata = tbasicdata;
		this.database = database;
		this.name = name;
		this.description = description;
		this.editable = editable;
		this.status = status;
		this.tbusinesspartners = tbusinesspartners;
		this.tbills = tbills;
		this.tbasicdatas = tbasicdatas;
		this.sroles = sroles;
		this.tbilldetails = tbilldetails;
		this.torderdetails = torderdetails;
		this.sgroups = sgroups;
		this.susers = susers;
		this.torders = torders;
		this.titems = titems;
		this.tbusinesspartneraddresses = tbusinesspartneraddresses;
	}

	@Id
	@Column(name = "idbasic", unique = true, nullable = false)
	public int getIdbasic() {
		return this.idbasic;
	}

	public void setIdbasic(int idbasic) {
		this.idbasic = idbasic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_idbasic", nullable = false)
	public Tbasicdata getTbasicdata() {
		return this.tbasicdata;
	}

	public void setTbasicdata(Tbasicdata tbasicdata) {
		this.tbasicdata = tbasicdata;
	}

	@Column(name = "database", nullable = false, length = 50)
	public String getDatabase() {
		return this.database;
	}

	public void setDatabase(String database) {
		this.database = database;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "editable", nullable = false)
	public boolean isEditable() {
		return this.editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTbusinesspartners() {
		return this.tbusinesspartners;
	}

	public void setTbusinesspartners(Set tbusinesspartners) {
		this.tbusinesspartners = tbusinesspartners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTbills() {
		return this.tbills;
	}

	public void setTbills(Set tbills) {
		this.tbills = tbills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTbasicdatas() {
		return this.tbasicdatas;
	}

	public void setTbasicdatas(Set tbasicdatas) {
		this.tbasicdatas = tbasicdatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getSroles() {
		return this.sroles;
	}

	public void setSroles(Set sroles) {
		this.sroles = sroles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTbilldetails() {
		return this.tbilldetails;
	}

	public void setTbilldetails(Set tbilldetails) {
		this.tbilldetails = tbilldetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTorderdetails() {
		return this.torderdetails;
	}

	public void setTorderdetails(Set torderdetails) {
		this.torderdetails = torderdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getSgroups() {
		return this.sgroups;
	}

	public void setSgroups(Set sgroups) {
		this.sgroups = sgroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getSusers() {
		return this.susers;
	}

	public void setSusers(Set susers) {
		this.susers = susers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTorders() {
		return this.torders;
	}

	public void setTorders(Set torders) {
		this.torders = torders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTitems() {
		return this.titems;
	}

	public void setTitems(Set titems) {
		this.titems = titems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbasicdata")
	public Set getTbusinesspartneraddresses() {
		return this.tbusinesspartneraddresses;
	}

	public void setTbusinesspartneraddresses(Set tbusinesspartneraddresses) {
		this.tbusinesspartneraddresses = tbusinesspartneraddresses;
	}

}
