package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbilldetail generated by hbm2java
 */
@Entity
@Table(name = "tbilldetail")
public class Tbilldetail implements java.io.Serializable {

	private int idbd;
	private Tbill tbill;
	private Titem titem;
	private String itemname;
	private float quantity;
	private float price;
	private float totalprice;
	private int status;

	public Tbilldetail() {
	}

	public Tbilldetail(int idbd, Tbill tbill, Titem titem, String itemname,
			float quantity, float price, float totalprice, int status) {
		this.idbd = idbd;
		this.tbill = tbill;
		this.titem = titem;
		this.itemname = itemname;
		this.quantity = quantity;
		this.price = price;
		this.totalprice = totalprice;
		this.status = status;
	}

	@Id
	@Column(name = "idbd", unique = true, nullable = false)
	public int getIdbd() {
		return this.idbd;
	}

	public void setIdbd(int idbd) {
		this.idbd = idbd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idb", nullable = false)
	public Tbill getTbill() {
		return this.tbill;
	}

	public void setTbill(Tbill tbill) {
		this.tbill = tbill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idite", nullable = false)
	public Titem getTitem() {
		return this.titem;
	}

	public void setTitem(Titem titem) {
		this.titem = titem;
	}

	@Column(name = "itemname", nullable = false, length = 100)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Column(name = "quantity", nullable = false, precision = 8, scale = 8)
	public float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(float quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 8, scale = 8)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "totalprice", nullable = false, precision = 8, scale = 8)
	public float getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(float totalprice) {
		this.totalprice = totalprice;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
