package database;

// Generated 10-oct-2012 10:59:39 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbusinesspartner generated by hbm2java
 */
@Entity
@Table(name = "tbusinesspartner")
public class Tbusinesspartner implements java.io.Serializable {

	private int idbp;
	private Tbasicdata tbasicdata;
	private String code;
	private String name;
	private String rif;
	private int riftype;
	private String contactperson;
	private String contactphone;
	private Set tbusinesspartneraddresses = new HashSet(0);
	private Set tbusinespartneritems = new HashSet(0);

	public Tbusinesspartner() {
	}

	public Tbusinesspartner(int idbp, Tbasicdata tbasicdata, String code,
			String name, String rif, int riftype) {
		this.idbp = idbp;
		this.tbasicdata = tbasicdata;
		this.code = code;
		this.name = name;
		this.rif = rif;
		this.riftype = riftype;
	}

	public Tbusinesspartner(int idbp, Tbasicdata tbasicdata, String code,
			String name, String rif, int riftype, String contactperson,
			String contactphone, Set tbusinesspartneraddresses,
			Set tbusinespartneritems) {
		this.idbp = idbp;
		this.tbasicdata = tbasicdata;
		this.code = code;
		this.name = name;
		this.rif = rif;
		this.riftype = riftype;
		this.contactperson = contactperson;
		this.contactphone = contactphone;
		this.tbusinesspartneraddresses = tbusinesspartneraddresses;
		this.tbusinespartneritems = tbusinespartneritems;
	}

	@Id
	@Column(name = "idbp", unique = true, nullable = false)
	public int getIdbp() {
		return this.idbp;
	}

	public void setIdbp(int idbp) {
		this.idbp = idbp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbasic", nullable = false)
	public Tbasicdata getTbasicdata() {
		return this.tbasicdata;
	}

	public void setTbasicdata(Tbasicdata tbasicdata) {
		this.tbasicdata = tbasicdata;
	}

	@Column(name = "code", nullable = false, length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rif", nullable = false, length = 15)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@Column(name = "riftype", nullable = false)
	public int getRiftype() {
		return this.riftype;
	}

	public void setRiftype(int riftype) {
		this.riftype = riftype;
	}

	@Column(name = "contactperson", length = 100)
	public String getContactperson() {
		return this.contactperson;
	}

	public void setContactperson(String contactperson) {
		this.contactperson = contactperson;
	}

	@Column(name = "contactphone", length = 15)
	public String getContactphone() {
		return this.contactphone;
	}

	public void setContactphone(String contactphone) {
		this.contactphone = contactphone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinesspartner")
	public Set getTbusinesspartneraddresses() {
		return this.tbusinesspartneraddresses;
	}

	public void setTbusinesspartneraddresses(Set tbusinesspartneraddresses) {
		this.tbusinesspartneraddresses = tbusinesspartneraddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinesspartner")
	public Set getTbusinespartneritems() {
		return this.tbusinespartneritems;
	}

	public void setTbusinespartneritems(Set tbusinespartneritems) {
		this.tbusinespartneritems = tbusinespartneritems;
	}

}
