package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbusinesspartneraddress generated by hbm2java
 */
@Entity
@Table(name = "tbusinesspartneraddress")
public class Tbusinesspartneraddress implements java.io.Serializable {

	private int idbpa;
	private Tbusinesspartner tbusinesspartner;
	private String name;
	private String addres;
	private String email;
	private int state;
	private int city;
	private String fax;
	private String phone;
	private int country;
	private int status;
	private Set torders = new HashSet(0);
	private Set tbills = new HashSet(0);

	public Tbusinesspartneraddress() {
	}

	public Tbusinesspartneraddress(int idbpa,
			Tbusinesspartner tbusinesspartner, String name, String addres,
			String email, int state, int city, String fax, String phone,
			int country, int status) {
		this.idbpa = idbpa;
		this.tbusinesspartner = tbusinesspartner;
		this.name = name;
		this.addres = addres;
		this.email = email;
		this.state = state;
		this.city = city;
		this.fax = fax;
		this.phone = phone;
		this.country = country;
		this.status = status;
	}

	public Tbusinesspartneraddress(int idbpa,
			Tbusinesspartner tbusinesspartner, String name, String addres,
			String email, int state, int city, String fax, String phone,
			int country, int status, Set torders, Set tbills) {
		this.idbpa = idbpa;
		this.tbusinesspartner = tbusinesspartner;
		this.name = name;
		this.addres = addres;
		this.email = email;
		this.state = state;
		this.city = city;
		this.fax = fax;
		this.phone = phone;
		this.country = country;
		this.status = status;
		this.torders = torders;
		this.tbills = tbills;
	}

	@Id
	@Column(name = "idbpa", unique = true, nullable = false)
	public int getIdbpa() {
		return this.idbpa;
	}

	public void setIdbpa(int idbpa) {
		this.idbpa = idbpa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbp", nullable = false)
	public Tbusinesspartner getTbusinesspartner() {
		return this.tbusinesspartner;
	}

	public void setTbusinesspartner(Tbusinesspartner tbusinesspartner) {
		this.tbusinesspartner = tbusinesspartner;
	}

	@Column(name = "name", nullable = false, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "addres", nullable = false, length = 200)
	public String getAddres() {
		return this.addres;
	}

	public void setAddres(String addres) {
		this.addres = addres;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "city", nullable = false)
	public int getCity() {
		return this.city;
	}

	public void setCity(int city) {
		this.city = city;
	}

	@Column(name = "fax", nullable = false, length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "country", nullable = false)
	public int getCountry() {
		return this.country;
	}

	public void setCountry(int country) {
		this.country = country;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinesspartneraddress")
	public Set getTorders() {
		return this.torders;
	}

	public void setTorders(Set torders) {
		this.torders = torders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinesspartneraddress")
	public Set getTbills() {
		return this.tbills;
	}

	public void setTbills(Set tbills) {
		this.tbills = tbills;
	}

}
