package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbusinesspartner generated by hbm2java
 */
@Entity
@Table(name = "tbusinesspartner")
public class Tbusinesspartner implements java.io.Serializable {

	private int idbp;
	private String code;
	private String name;
	private String rif;
	private int riftype;
	private int type;
	private String address;
	private int status;
	private Set tbusinesspartneraddresses = new HashSet(0);
	private Set tbusinespartneritems = new HashSet(0);

	public Tbusinesspartner() {
	}

	public Tbusinesspartner(int idbp, String code, String name, String rif,
			int riftype, int type, String address, int status) {
		this.idbp = idbp;
		this.code = code;
		this.name = name;
		this.rif = rif;
		this.riftype = riftype;
		this.type = type;
		this.address = address;
		this.status = status;
	}

	public Tbusinesspartner(int idbp, String code, String name, String rif,
			int riftype, int type, String address, int status,
			Set tbusinesspartneraddresses, Set tbusinespartneritems) {
		this.idbp = idbp;
		this.code = code;
		this.name = name;
		this.rif = rif;
		this.riftype = riftype;
		this.type = type;
		this.address = address;
		this.status = status;
		this.tbusinesspartneraddresses = tbusinesspartneraddresses;
		this.tbusinespartneritems = tbusinespartneritems;
	}

	@Id
	@Column(name = "idbp", unique = true, nullable = false)
	public int getIdbp() {
		return this.idbp;
	}

	public void setIdbp(int idbp) {
		this.idbp = idbp;
	}

	@Column(name = "code", nullable = false, length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rif", nullable = false, length = 15)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@Column(name = "riftype", nullable = false)
	public int getRiftype() {
		return this.riftype;
	}

	public void setRiftype(int riftype) {
		this.riftype = riftype;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinesspartner")
	public Set getTbusinesspartneraddresses() {
		return this.tbusinesspartneraddresses;
	}

	public void setTbusinesspartneraddresses(Set tbusinesspartneraddresses) {
		this.tbusinesspartneraddresses = tbusinesspartneraddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinesspartner")
	public Set getTbusinespartneritems() {
		return this.tbusinespartneritems;
	}

	public void setTbusinespartneritems(Set tbusinespartneritems) {
		this.tbusinespartneritems = tbusinespartneritems;
	}

}
