package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbusinespartneritemId generated by hbm2java
 */
@Embeddable
public class TbusinespartneritemId implements java.io.Serializable {

	private int idbp;
	private int idite;

	public TbusinespartneritemId() {
	}

	public TbusinespartneritemId(int idbp, int idite) {
		this.idbp = idbp;
		this.idite = idite;
	}

	@Column(name = "idbp", nullable = false)
	public int getIdbp() {
		return this.idbp;
	}

	public void setIdbp(int idbp) {
		this.idbp = idbp;
	}

	@Column(name = "idite", nullable = false)
	public int getIdite() {
		return this.idite;
	}

	public void setIdite(int idite) {
		this.idite = idite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbusinespartneritemId))
			return false;
		TbusinespartneritemId castOther = (TbusinespartneritemId) other;

		return (this.getIdbp() == castOther.getIdbp())
				&& (this.getIdite() == castOther.getIdite());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdbp();
		result = 37 * result + this.getIdite();
		return result;
	}

}
