package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbusinespartneritem generated by hbm2java
 */
@Entity
@Table(name = "tbusinespartneritem")
public class Tbusinespartneritem implements java.io.Serializable {

	private TbusinespartneritemId id;
	private Tbusinesspartner tbusinesspartner;
	private Titem titem;
	private int status;

	public Tbusinespartneritem() {
	}

	public Tbusinespartneritem(TbusinespartneritemId id,
			Tbusinesspartner tbusinesspartner, Titem titem, int status) {
		this.id = id;
		this.tbusinesspartner = tbusinesspartner;
		this.titem = titem;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idbp", column = @Column(name = "idbp", nullable = false)),
			@AttributeOverride(name = "idite", column = @Column(name = "idite", nullable = false)) })
	public TbusinespartneritemId getId() {
		return this.id;
	}

	public void setId(TbusinespartneritemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbp", nullable = false, insertable = false, updatable = false)
	public Tbusinesspartner getTbusinesspartner() {
		return this.tbusinesspartner;
	}

	public void setTbusinesspartner(Tbusinesspartner tbusinesspartner) {
		this.tbusinesspartner = tbusinesspartner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idite", nullable = false, insertable = false, updatable = false)
	public Titem getTitem() {
		return this.titem;
	}

	public void setTitem(Titem titem) {
		this.titem = titem;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
