package database;

// Generated 10-oct-2012 10:59:39 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Titem generated by hbm2java
 */
@Entity
@Table(name = "titem")
public class Titem implements java.io.Serializable {

	private int idite;
	private Tbasicdata tbasicdata;
	private String code;
	private String name;
	private boolean washable;
	private float cost;
	private float price;
	private int unitcart;
	private int volumenunit;
	private Set torderdetails = new HashSet(0);
	private Set tbusinespartneritems = new HashSet(0);
	private Set tbilldetails = new HashSet(0);

	public Titem() {
	}

	public Titem(int idite, Tbasicdata tbasicdata, String code, String name,
			boolean washable, float cost, float price, int unitcart,
			int volumenunit) {
		this.idite = idite;
		this.tbasicdata = tbasicdata;
		this.code = code;
		this.name = name;
		this.washable = washable;
		this.cost = cost;
		this.price = price;
		this.unitcart = unitcart;
		this.volumenunit = volumenunit;
	}

	public Titem(int idite, Tbasicdata tbasicdata, String code, String name,
			boolean washable, float cost, float price, int unitcart,
			int volumenunit, Set torderdetails, Set tbusinespartneritems,
			Set tbilldetails) {
		this.idite = idite;
		this.tbasicdata = tbasicdata;
		this.code = code;
		this.name = name;
		this.washable = washable;
		this.cost = cost;
		this.price = price;
		this.unitcart = unitcart;
		this.volumenunit = volumenunit;
		this.torderdetails = torderdetails;
		this.tbusinespartneritems = tbusinespartneritems;
		this.tbilldetails = tbilldetails;
	}

	@Id
	@Column(name = "idite", unique = true, nullable = false)
	public int getIdite() {
		return this.idite;
	}

	public void setIdite(int idite) {
		this.idite = idite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbasic", nullable = false)
	public Tbasicdata getTbasicdata() {
		return this.tbasicdata;
	}

	public void setTbasicdata(Tbasicdata tbasicdata) {
		this.tbasicdata = tbasicdata;
	}

	@Column(name = "code", nullable = false, length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "washable", nullable = false)
	public boolean isWashable() {
		return this.washable;
	}

	public void setWashable(boolean washable) {
		this.washable = washable;
	}

	@Column(name = "cost", nullable = false, precision = 8, scale = 8)
	public float getCost() {
		return this.cost;
	}

	public void setCost(float cost) {
		this.cost = cost;
	}

	@Column(name = "price", nullable = false, precision = 8, scale = 8)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "unitcart", nullable = false)
	public int getUnitcart() {
		return this.unitcart;
	}

	public void setUnitcart(int unitcart) {
		this.unitcart = unitcart;
	}

	@Column(name = "volumenunit", nullable = false)
	public int getVolumenunit() {
		return this.volumenunit;
	}

	public void setVolumenunit(int volumenunit) {
		this.volumenunit = volumenunit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set getTorderdetails() {
		return this.torderdetails;
	}

	public void setTorderdetails(Set torderdetails) {
		this.torderdetails = torderdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set getTbusinespartneritems() {
		return this.tbusinespartneritems;
	}

	public void setTbusinespartneritems(Set tbusinespartneritems) {
		this.tbusinespartneritems = tbusinespartneritems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set getTbilldetails() {
		return this.tbilldetails;
	}

	public void setTbilldetails(Set tbilldetails) {
		this.tbilldetails = tbilldetails;
	}

}
