package database;

// Generated 08-oct-2012 11:54:36 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Torder generated by hbm2java
 */
@Entity
@Table(name = "torder")
public class Torder implements java.io.Serializable {

	private int ido;
	private Tbusinesspartneraddress tbusinesspartneraddress;
	private String ordernumber;
	private String bpname;
	private Date orderdate;
	private Date deliverydate;
	private String rif;
	private String address;
	private int type;
	private float ordertotal;
	private float taxtotal;
	private int status;
	private Set tbills = new HashSet(0);
	private Set torderdetails = new HashSet(0);

	public Torder() {
	}

	public Torder(int ido, Tbusinesspartneraddress tbusinesspartneraddress,
			String ordernumber, String bpname, Date orderdate,
			Date deliverydate, String rif, String address, int type,
			float ordertotal, float taxtotal, int status) {
		this.ido = ido;
		this.tbusinesspartneraddress = tbusinesspartneraddress;
		this.ordernumber = ordernumber;
		this.bpname = bpname;
		this.orderdate = orderdate;
		this.deliverydate = deliverydate;
		this.rif = rif;
		this.address = address;
		this.type = type;
		this.ordertotal = ordertotal;
		this.taxtotal = taxtotal;
		this.status = status;
	}

	public Torder(int ido, Tbusinesspartneraddress tbusinesspartneraddress,
			String ordernumber, String bpname, Date orderdate,
			Date deliverydate, String rif, String address, int type,
			float ordertotal, float taxtotal, int status, Set tbills,
			Set torderdetails) {
		this.ido = ido;
		this.tbusinesspartneraddress = tbusinesspartneraddress;
		this.ordernumber = ordernumber;
		this.bpname = bpname;
		this.orderdate = orderdate;
		this.deliverydate = deliverydate;
		this.rif = rif;
		this.address = address;
		this.type = type;
		this.ordertotal = ordertotal;
		this.taxtotal = taxtotal;
		this.status = status;
		this.tbills = tbills;
		this.torderdetails = torderdetails;
	}

	@Id
	@Column(name = "ido", unique = true, nullable = false)
	public int getIdo() {
		return this.ido;
	}

	public void setIdo(int ido) {
		this.ido = ido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbpa", nullable = false)
	public Tbusinesspartneraddress getTbusinesspartneraddress() {
		return this.tbusinesspartneraddress;
	}

	public void setTbusinesspartneraddress(
			Tbusinesspartneraddress tbusinesspartneraddress) {
		this.tbusinesspartneraddress = tbusinesspartneraddress;
	}

	@Column(name = "ordernumber", nullable = false, length = 12)
	public String getOrdernumber() {
		return this.ordernumber;
	}

	public void setOrdernumber(String ordernumber) {
		this.ordernumber = ordernumber;
	}

	@Column(name = "bpname", nullable = false, length = 100)
	public String getBpname() {
		return this.bpname;
	}

	public void setBpname(String bpname) {
		this.bpname = bpname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "orderdate", nullable = false, length = 29)
	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deliverydate", nullable = false, length = 29)
	public Date getDeliverydate() {
		return this.deliverydate;
	}

	public void setDeliverydate(Date deliverydate) {
		this.deliverydate = deliverydate;
	}

	@Column(name = "rif", nullable = false, length = 15)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "ordertotal", nullable = false, precision = 8, scale = 8)
	public float getOrdertotal() {
		return this.ordertotal;
	}

	public void setOrdertotal(float ordertotal) {
		this.ordertotal = ordertotal;
	}

	@Column(name = "taxtotal", nullable = false, precision = 8, scale = 8)
	public float getTaxtotal() {
		return this.taxtotal;
	}

	public void setTaxtotal(float taxtotal) {
		this.taxtotal = taxtotal;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torder")
	public Set getTbills() {
		return this.tbills;
	}

	public void setTbills(Set tbills) {
		this.tbills = tbills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torder")
	public Set getTorderdetails() {
		return this.torderdetails;
	}

	public void setTorderdetails(Set torderdetails) {
		this.torderdetails = torderdetails;
	}

}
