package database;

// Generated 10-oct-2012 10:59:39 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Torderdetail generated by hbm2java
 */
@Entity
@Table(name = "torderdetail")
public class Torderdetail implements java.io.Serializable {

	private int idod;
	private Tbasicdata tbasicdata;
	private Torder torder;
	private Titem titem;
	private String itemname;
	private float quantity;
	private float price;
	private float totalprice;

	public Torderdetail() {
	}

	public Torderdetail(int idod, Tbasicdata tbasicdata, Torder torder,
			Titem titem, String itemname, float quantity, float price,
			float totalprice) {
		this.idod = idod;
		this.tbasicdata = tbasicdata;
		this.torder = torder;
		this.titem = titem;
		this.itemname = itemname;
		this.quantity = quantity;
		this.price = price;
		this.totalprice = totalprice;
	}

	@Id
	@Column(name = "idod", unique = true, nullable = false)
	public int getIdod() {
		return this.idod;
	}

	public void setIdod(int idod) {
		this.idod = idod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbasic", nullable = false)
	public Tbasicdata getTbasicdata() {
		return this.tbasicdata;
	}

	public void setTbasicdata(Tbasicdata tbasicdata) {
		this.tbasicdata = tbasicdata;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ido", nullable = false)
	public Torder getTorder() {
		return this.torder;
	}

	public void setTorder(Torder torder) {
		this.torder = torder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idite", nullable = false)
	public Titem getTitem() {
		return this.titem;
	}

	public void setTitem(Titem titem) {
		this.titem = titem;
	}

	@Column(name = "itemname", nullable = false, length = 100)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Column(name = "quantity", nullable = false, precision = 8, scale = 8)
	public float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(float quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 8, scale = 8)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "totalprice", nullable = false, precision = 8, scale = 8)
	public float getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(float totalprice) {
		this.totalprice = totalprice;
	}

}
