package models;

// Generated 24/01/2013 03:33:32 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * SecurityRole generated by hbm2java
 */
@Entity
@Table(name = "security_role")
public class SecurityRole implements java.io.Serializable {

	private int idSecurityRole;
	private String name;
	private String description;
	private short status;
	private Set<SecurityGroup> securityGroups = new HashSet<SecurityGroup>(0);

	public SecurityRole() {
	}

	public SecurityRole(int idSecurityRole, String name, String description,
			short status) {
		this.idSecurityRole = idSecurityRole;
		this.name = name;
		this.description = description;
		this.status = status;
	}

	public SecurityRole(int idSecurityRole, String name, String description,
			short status, Set<SecurityGroup> securityGroups) {
		this.idSecurityRole = idSecurityRole;
		this.name = name;
		this.description = description;
		this.status = status;
		this.securityGroups = securityGroups;
	}

	@Id
	@Column(name = "id_security_role", unique = true, nullable = false)
	public int getIdSecurityRole() {
		return this.idSecurityRole;
	}

	public void setIdSecurityRole(int idSecurityRole) {
		this.idSecurityRole = idSecurityRole;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "role_group", joinColumns = { @JoinColumn(name = "id_security_role", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_security_group", nullable = false, updatable = false) })
	public Set<SecurityGroup> getSecurityGroups() {
		return this.securityGroups;
	}

	public void setSecurityGroups(Set<SecurityGroup> securityGroups) {
		this.securityGroups = securityGroups;
	}

}
