package models;

// Generated 14/07/2014 10:49:25 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TbusinessPartnerBranch generated by hbm2java
 */
@Entity
@Table(name = "tbusiness_partner_branch", schema = "public")
public class TbusinessPartnerBranch implements java.io.Serializable {

	private static final long serialVersionUID = 2202688424863643527L;
	private int idBusinessPartnerBranch;
	private TbusinessPartner tbusinessPartner;
	private TbasicData tbasicData;
	private String name;
	private String address;
	private String email;
	private String fax;
	private String contactPhone;
	private String contactName;
	private boolean addressDefault;
	private Set<Torder> torders = new HashSet<Torder>(0);
	private Set<Tbill> tbills = new HashSet<Tbill>(0);

	public TbusinessPartnerBranch() {
	}

	public TbusinessPartnerBranch(int idBusinessPartnerBranch, TbusinessPartner tbusinessPartner, TbasicData tbasicData, String name, String address, String contactPhone, String contactName, boolean addressDefault) {
		this.idBusinessPartnerBranch = idBusinessPartnerBranch;
		this.tbusinessPartner = tbusinessPartner;
		this.tbasicData = tbasicData;
		this.name = name;
		this.address = address;
		this.contactPhone = contactPhone;
		this.contactName = contactName;
		this.addressDefault = addressDefault;
	}

	public TbusinessPartnerBranch(int idBusinessPartnerBranch, TbusinessPartner tbusinessPartner, TbasicData tbasicData, String name, String address, String email, String fax, String contactPhone, String contactName, boolean addressDefault, Set<Torder> torders, Set<Tbill> tbills) {
		this.idBusinessPartnerBranch = idBusinessPartnerBranch;
		this.tbusinessPartner = tbusinessPartner;
		this.tbasicData = tbasicData;
		this.name = name;
		this.address = address;
		this.email = email;
		this.fax = fax;
		this.contactPhone = contactPhone;
		this.contactName = contactName;
		this.addressDefault = addressDefault;
		this.torders = torders;
		this.tbills = tbills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "tbusiness_partner_branch_id_seq")
    @SequenceGenerator(name = "tbusiness_partner_branch_id_seq", sequenceName = "tbusiness_partner_branch_id_seq")
	@Column(name = "id_business_partner_branch", unique = true, nullable = false)
	public int getIdBusinessPartnerBranch() {
		return this.idBusinessPartnerBranch;
	}

	public void setIdBusinessPartnerBranch(int idBusinessPartnerBranch) {
		this.idBusinessPartnerBranch = idBusinessPartnerBranch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_business_partner", nullable = false)
	public TbusinessPartner getTbusinessPartner() {
		return this.tbusinessPartner;
	}

	public void setTbusinessPartner(TbusinessPartner tbusinessPartner) {
		this.tbusinessPartner = tbusinessPartner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city", nullable = false)
	public TbasicData getTbasicData() {
		return this.tbasicData;
	}

	public void setTbasicData(TbasicData tbasicData) {
		this.tbasicData = tbasicData;
	}

	@Column(name = "name", nullable = false, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "contact_phone", nullable = false, length = 15)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "contact_name", nullable = false, length = 100)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "address_default", nullable = false)
	public boolean isAddressDefault() {
		return this.addressDefault;
	}

	public void setAddressDefault(boolean addressDefault) {
		this.addressDefault = addressDefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinessPartnerBranch")
	public Set<Torder> getTorders() {
		return this.torders;
	}

	public void setTorders(Set<Torder> torders) {
		this.torders = torders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbusinessPartnerBranch")
	public Set<Tbill> getTbills() {
		return this.tbills;
	}

	public void setTbills(Set<Tbill> tbills) {
		this.tbills = tbills;
	}

}
