package models;

// Generated 17/12/2014 05:36:53 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbusinessPartnerRoute generated by hbm2java
 */
@Entity
@Table(name = "tbusiness_partner_route", schema = "public")
public class TbusinessPartnerRoute implements java.io.Serializable {

	private static final long serialVersionUID = 2161309943703836334L;
	private TbusinessPartnerRouteId id;
	private Troute troute;
	private TbusinessPartnerBranch tbusinessPartnerBranch;
	private char status;

	public TbusinessPartnerRoute() {
	}

	public TbusinessPartnerRoute(TbusinessPartnerRouteId id, Troute troute, TbusinessPartnerBranch tbusinessPartnerBranch, char status) {
		this.id = id;
		this.troute = troute;
		this.tbusinessPartnerBranch = tbusinessPartnerBranch;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idRoute", column = @Column(name = "id_route", nullable = false)), @AttributeOverride(name = "idBusinessPartnerBranch", column = @Column(name = "id_business_partner_branch", nullable = false)) })
	public TbusinessPartnerRouteId getId() {
		return this.id;
	}

	public void setId(TbusinessPartnerRouteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_route", nullable = false, insertable = false, updatable = false)
	public Troute getTroute() {
		return this.troute;
	}

	public void setTroute(Troute troute) {
		this.troute = troute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_business_partner_branch", nullable = false, insertable = false, updatable = false)
	public TbusinessPartnerBranch getTbusinessPartnerBranch() {
		return this.tbusinessPartnerBranch;
	}

	public void setTbusinessPartnerBranch(TbusinessPartnerBranch tbusinessPartnerBranch) {
		this.tbusinessPartnerBranch = tbusinessPartnerBranch;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
