package models;

// Generated 17/12/2014 05:36:53 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbusinessPartnerRouteId generated by hbm2java
 */
@Embeddable
public class TbusinessPartnerRouteId implements java.io.Serializable {

	private static final long serialVersionUID = 5318719755500812877L;
	private int idRoute;
	private int idBusinessPartnerBranch;

	public TbusinessPartnerRouteId() {
	}

	public TbusinessPartnerRouteId(int idRoute, int idBusinessPartnerBranch) {
		this.idRoute = idRoute;
		this.idBusinessPartnerBranch = idBusinessPartnerBranch;
	}

	@Column(name = "id_route", nullable = false)
	public int getIdRoute() {
		return this.idRoute;
	}

	public void setIdRoute(int idRoute) {
		this.idRoute = idRoute;
	}

	@Column(name = "id_business_partner_branch", nullable = false)
	public int getIdBusinessPartnerBranch() {
		return this.idBusinessPartnerBranch;
	}

	public void setIdBusinessPartnerBranch(int idBusinessPartnerBranch) {
		this.idBusinessPartnerBranch = idBusinessPartnerBranch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbusinessPartnerRouteId))
			return false;
		TbusinessPartnerRouteId castOther = (TbusinessPartnerRouteId) other;

		return (this.getIdRoute() == castOther.getIdRoute()) && (this.getIdBusinessPartnerBranch() == castOther.getIdBusinessPartnerBranch());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRoute();
		result = 37 * result + this.getIdBusinessPartnerBranch();
		return result;
	}

}
