package models;

// Generated 03/09/2014 09:02:10 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Titem generated by hbm2java
 */
@Entity
@Table(name = "titem", schema = "public")
public class Titem implements java.io.Serializable {

	private static final long serialVersionUID = -1578598571902014726L;
	private int idItem;
	private TbasicData tbasicData;
	private String code;
	private String name;
	private boolean washable;
	private char status;
	private Set<TorderDetail> torderDetails = new HashSet<TorderDetail>(0);
	private Set<ToutputMeasureUnit> toutputMeasureUnits = new HashSet<ToutputMeasureUnit>(0);
	private Set<TbusinesPartnerItem> tbusinesPartnerItems = new HashSet<TbusinesPartnerItem>(0);
	private Set<TpurchaseDetail> tpurchaseDetails = new HashSet<TpurchaseDetail>(0);
	private Set<TinputMeasureUnit> tinputMeasureUnits = new HashSet<TinputMeasureUnit>(0);

	public Titem() {
	}

	public Titem(int idItem, TbasicData tbasicData, String code, String name, boolean washable, char status) {
		this.idItem = idItem;
		this.tbasicData = tbasicData;
		this.code = code;
		this.name = name;
		this.washable = washable;
		this.status = status;
	}

	public Titem(int idItem, TbasicData tbasicData, String code, String name, boolean washable, char status, Set<TorderDetail> torderDetails, Set<ToutputMeasureUnit> toutputMeasureUnits, Set<TbusinesPartnerItem> tbusinesPartnerItems, Set<TpurchaseDetail> tpurchaseDetails, Set<TinputMeasureUnit> tinputMeasureUnits) {
		this.idItem = idItem;
		this.tbasicData = tbasicData;
		this.code = code;
		this.name = name;
		this.washable = washable;
		this.status = status;
		this.torderDetails = torderDetails;
		this.toutputMeasureUnits = toutputMeasureUnits;
		this.tbusinesPartnerItems = tbusinesPartnerItems;
		this.tpurchaseDetails = tpurchaseDetails;
		this.tinputMeasureUnits = tinputMeasureUnits;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "titem_id_seq")
    @SequenceGenerator(name = "titem_id_seq", sequenceName = "titem_id_seq")
	@Column(name = "id_item", unique = true, nullable = false)
	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public TbasicData getTbasicData() {
		return this.tbasicData;
	}

	public void setTbasicData(TbasicData tbasicData) {
		this.tbasicData = tbasicData;
	}

	@Column(name = "code", nullable = false, length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "washable", nullable = false)
	public boolean isWashable() {
		return this.washable;
	}

	public void setWashable(boolean washable) {
		this.washable = washable;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set<TorderDetail> getTorderDetails() {
		return this.torderDetails;
	}

	public void setTorderDetails(Set<TorderDetail> torderDetails) {
		this.torderDetails = torderDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set<ToutputMeasureUnit> getToutputMeasureUnits() {
		return this.toutputMeasureUnits;
	}

	public void setToutputMeasureUnits(Set<ToutputMeasureUnit> toutputMeasureUnits) {
		this.toutputMeasureUnits = toutputMeasureUnits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set<TbusinesPartnerItem> getTbusinesPartnerItems() {
		return this.tbusinesPartnerItems;
	}

	public void setTbusinesPartnerItems(Set<TbusinesPartnerItem> tbusinesPartnerItems) {
		this.tbusinesPartnerItems = tbusinesPartnerItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set<TpurchaseDetail> getTpurchaseDetails() {
		return this.tpurchaseDetails;
	}

	public void setTpurchaseDetails(Set<TpurchaseDetail> tpurchaseDetails) {
		this.tpurchaseDetails = tpurchaseDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titem")
	public Set<TinputMeasureUnit> getTinputMeasureUnits() {
		return this.tinputMeasureUnits;
	}

	public void setTinputMeasureUnits(Set<TinputMeasureUnit> tinputMeasureUnits) {
		this.tinputMeasureUnits = tinputMeasureUnits;
	}

}
