package models;

// Generated 01/08/2014 10:16:18 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TorderNumber generated by hbm2java
 */
@Entity
@Table(name = "torder_number", schema = "public")
public class TorderNumber implements java.io.Serializable {

	private static final long serialVersionUID = 6116382577303014934L;
	private int idOrderNumber;
	private char status;
	private Set<Torder> torders = new HashSet<Torder>(0);

	public TorderNumber() {
	}

	public TorderNumber(int idOrderNumber, char status) {
		this.idOrderNumber = idOrderNumber;
		this.status = status;
	}

	public TorderNumber(int idOrderNumber, char status, Set<Torder> torders) {
		this.idOrderNumber = idOrderNumber;
		this.status = status;
		this.torders = torders;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "torder_number_id_seq")
	@SequenceGenerator(name = "torder_number_id_seq", sequenceName = "torder_number_id_order_number_seq")
	@Column(name = "id_order_number", unique = true, nullable = false)
	public int getIdOrderNumber() {
		return this.idOrderNumber;
	}

	public void setIdOrderNumber(int idOrderNumber) {
		this.idOrderNumber = idOrderNumber;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "torderNumber")
	public Set<Torder> getTorders() {
		return this.torders;
	}

	public void setTorders(Set<Torder> torders) {
		this.torders = torders;
	}

}
