package models;

// Generated 21/09/2014 11:58:57 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpurchaseDetail generated by hbm2java
 */
@Entity
@Table(name = "tpurchase_detail", schema = "public")
public class TpurchaseDetail implements java.io.Serializable {

	private static final long serialVersionUID = -7901127062084404923L;
	private int idPurchaseDetail;
	private Tpurchase tpurchase;
	private Titem titem;
	private TbasicData tbasicData;
	private String itemName;
	private float quantity;
	private float price;
	private float totalPrice;
	private float missingQuantity;
	private char status;

	public TpurchaseDetail() {
	}

	public TpurchaseDetail(int idPurchaseDetail, Tpurchase tpurchase, Titem titem, TbasicData tbasicData, String itemName, float quantity, float price, float totalPrice, float missingQuantity, char status) {
		this.idPurchaseDetail = idPurchaseDetail;
		this.tpurchase = tpurchase;
		this.titem = titem;
		this.tbasicData = tbasicData;
		this.itemName = itemName;
		this.quantity = quantity;
		this.price = price;
		this.totalPrice = totalPrice;
		this.missingQuantity = missingQuantity;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "tpurchase_detail_id_seq")
	@SequenceGenerator(name = "tpurchase_detail_id_seq", sequenceName = "tpurchase_detail_id_purchase_detail_seq")
	@Column(name = "id_purchase_detail", unique = true, nullable = false)
	public int getIdPurchaseDetail() {
		return this.idPurchaseDetail;
	}

	public void setIdPurchaseDetail(int idPurchaseDetail) {
		this.idPurchaseDetail = idPurchaseDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_purchase", nullable = false)
	public Tpurchase getTpurchase() {
		return this.tpurchase;
	}

	public void setTpurchase(Tpurchase tpurchase) {
		this.tpurchase = tpurchase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_item", nullable = false)
	public Titem getTitem() {
		return this.titem;
	}

	public void setTitem(Titem titem) {
		this.titem = titem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measure_unit", nullable = false)
	public TbasicData getTbasicData() {
		return this.tbasicData;
	}

	public void setTbasicData(TbasicData tbasicData) {
		this.tbasicData = tbasicData;
	}

	@Column(name = "item_name", nullable = false, length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "quantity", nullable = false, precision = 8, scale = 8)
	public float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(float quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 8, scale = 8)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "total_price", nullable = false, precision = 8, scale = 8)
	public float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "missing_quantity", nullable = false, precision = 8, scale = 8)
	public float getMissingQuantity() {
		return this.missingQuantity;
	}

	public void setMissingQuantity(float missingQuantity) {
		this.missingQuantity = missingQuantity;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
