package models;

// Generated 17/12/2014 05:36:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Troute generated by hbm2java
 */
@Entity
@Table(name = "troute", schema = "public")
public class Troute implements java.io.Serializable {

	private static final long serialVersionUID = -8475231006609560337L;
	private int idRoute;
	private int code;
	private String description;
	private char status;
	private Set<TbusinessPartnerRoute> tbusinessPartnerRoutes = new HashSet<TbusinessPartnerRoute>(0);
	private Set<Twaybill> twaybills = new HashSet<Twaybill>(0);

	public Troute() {
	}

	public Troute(int idRoute, int code, String description, char status) {
		this.idRoute = idRoute;
		this.code = code;
		this.description = description;
		this.status = status;
	}

	public Troute(int idRoute, int code, String description, char status, Set<TbusinessPartnerRoute> tbusinessPartnerRoutes, Set<Twaybill> twaybills) {
		this.idRoute = idRoute;
		this.code = code;
		this.description = description;
		this.status = status;
		this.tbusinessPartnerRoutes = tbusinessPartnerRoutes;
		this.twaybills = twaybills;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "troute_id_seq")
	@SequenceGenerator(name = "troute_id_seq", sequenceName = "troute_id_route_seq")
	@Column(name = "id_route", unique = true, nullable = false)
	public int getIdRoute() {
		return this.idRoute;
	}

	public void setIdRoute(int idRoute) {
		this.idRoute = idRoute;
	}

	/**
	* <b>@Generated</B> con generationTime.ALWAYS es la forma de autoincrementar el campo cuando el campo no es
	* primario, y la base de datos le ha asignado una secuencia incrementable.
	*
	* @return
	*/
	@Generated(GenerationTime.ALWAYS)
	@Column(name = "code", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false, length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "troute")
	public Set<TbusinessPartnerRoute> getTbusinessPartnerRoutes() {
		return this.tbusinessPartnerRoutes;
	}

	public void setTbusinessPartnerRoutes(Set<TbusinessPartnerRoute> tbusinessPartnerRoutes) {
		this.tbusinessPartnerRoutes = tbusinessPartnerRoutes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "troute")
	public Set<Twaybill> getTwaybills() {
		return this.twaybills;
	}

	public void setTwaybills(Set<Twaybill> twaybills) {
		this.twaybills = twaybills;
	}

}
